const serviceTypes = [
  { label: 'Plumbing Services', value: 'Plumbing Services' },
  { label: 'Hair Dressing', value: 'Hair Dressing' },
  { label: 'Auto Mechanic', value: 'Auto Mechanic' },
  { label: 'Bike Delivery Rider', value: 'Bike Delivery Rider' },
  { label: 'Carpentry', value: 'Carpentry' },
  { label: 'Electrical Services', value: 'Electrical Services' },
  { label: 'House Cleaning', value: 'House Cleaning' },
  { label: 'Gardening and Landscaping', value: 'Gardening and Landscaping' },
  { label: 'Tutoring', value: 'Tutoring' },
  { label: 'Fitness Trainer', value: 'Fitness Trainer' },
  { label: 'Catering Services', value: 'Catering Services' },
  { label: 'Photography', value: 'Photography' },
  { label: 'Graphic Design', value: 'Graphic Design' },
  { label: 'Web Development', value: 'Web Development' },
  { label: 'Interior Design', value: 'Interior Design' },
  { label: 'Makeup Artist', value: 'Makeup Artist' },
  { label: 'Event Planning', value: 'Event Planning' },
  { label: 'Pet Grooming', value: 'Pet Grooming' },
  { label: 'Home Painting', value: 'Home Painting' },
  { label: 'Car Washing', value: 'Car Washing' },
  { label: 'Tailoring', value: 'Tailoring' },
];

export default serviceTypes;
